# Generated by Django 3.2.3 on 2021-05-27 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('max_way', '0005_auto_20210527_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minimage',
            name='min_image',
            field=models.FileField(upload_to='imoges/'),
        ),
    ]
