# Generated by Django 3.2.3 on 2021-05-27 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('max_way', '0006_alter_minimage_min_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='min_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='max_way.minimage'),
        ),
    ]
